// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSCFFo8P8V1QfJoTI6lNNHDRXp7av0i0M',
    appId: '1:70400900438:web:291e5b2b906bfdab43aaf7',
    messagingSenderId: '70400900438',
    projectId: 'rutvij-6b6fe',
    authDomain: 'rutvij-6b6fe.firebaseapp.com',
    storageBucket: 'rutvij-6b6fe.firebasestorage.app',
    measurementId: 'G-NQ609SJEWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDBYMClyX2qXlo9TE-GC6N3cDSJNG_7Jg',
    appId: '1:70400900438:android:88006878cf9fda0543aaf7',
    messagingSenderId: '70400900438',
    projectId: 'rutvij-6b6fe',
    storageBucket: 'rutvij-6b6fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeB4vtvwq6CZWrMjH8colxe_1vCxEThAc',
    appId: '1:70400900438:ios:5a9b45df8444256743aaf7',
    messagingSenderId: '70400900438',
    projectId: 'rutvij-6b6fe',
    storageBucket: 'rutvij-6b6fe.firebasestorage.app',
    androidClientId: '70400900438-d6cf5ue9m0tdqhukg9uafnondri63vcp.apps.googleusercontent.com',
    iosClientId: '70400900438-irai0c1d1u899djap27otte1bbd6op5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeB4vtvwq6CZWrMjH8colxe_1vCxEThAc',
    appId: '1:70400900438:ios:5a9b45df8444256743aaf7',
    messagingSenderId: '70400900438',
    projectId: 'rutvij-6b6fe',
    storageBucket: 'rutvij-6b6fe.firebasestorage.app',
    androidClientId: '70400900438-d6cf5ue9m0tdqhukg9uafnondri63vcp.apps.googleusercontent.com',
    iosClientId: '70400900438-irai0c1d1u899djap27otte1bbd6op5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSCFFo8P8V1QfJoTI6lNNHDRXp7av0i0M',
    appId: '1:70400900438:web:0b1d7d2c2a77e27143aaf7',
    messagingSenderId: '70400900438',
    projectId: 'rutvij-6b6fe',
    authDomain: 'rutvij-6b6fe.firebaseapp.com',
    storageBucket: 'rutvij-6b6fe.firebasestorage.app',
    measurementId: 'G-1CDZXBRM9Q',
  );
}
